version: 2
jobs:
  build:
    working_repositories: ~/repositories
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs"
      - run:
          name: Setup SSH for AWS CodeCommit
          command: |
            chmod +x scripts/setup-ssh.sh
            scripts/setup-ssh.sh  devops-aman-at-467487045317  US-WEST-2
      - run:
          name: Mirror Github Repositories to AWS CodeCommit
          command: pipenv run python3 src/github-aws-commit-mirror.py

workflows:
  version: 2
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *" # Trigger every night at 00:00
          filters:
            branches:
              only:
                - master
